### ISSUE TITLE
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4137 tokens. Please reduce the length of the messages.

### ISSUE THREAD

**Issue by nanato12** [nanato12/chatgpt-linebot-python#7]
```
127.0.0.1 - - [15/Mar/2023 02:17:39] "POST /callback HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/app/__init__.py", line 38, in callback
    handler.handle(body, signature)
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/linebot/webhook.py", line 263, in handle
    self.__invoke_func(func, event, payload)
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/linebot/webhook.py", line 275, in __invoke_func
    func(event)
  File "/Users/macuser/github/chatgpt-linebot-python/app/__init__.py", line 57, in handle_message
    res = gpt_client.create()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/app/gpt/client.py", line 28, in create
    res = openai.ChatCompletion.create(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/macuser/github/chatgpt-linebot-python/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4137 tokens. Please reduce the length of the messages.
```

**Comment by nanato12** [comment]
会話続くようにしたからinputのメッセージがめちゃくちゃ長くなったぽい
やっぱリセットできる機能をつけるしかなさそうだね
